[start]
cmd = "reflex run --env prod --backend-host 0.0.0.0 --backend-port $PORT"

[phases.setup]
nixPkgs = ["unzip", "curl", "python312"]

[phases.install]
# Evita instalar dependencias frontend en Railway
cmds = []

[phases.build]
cmds = []

[phases.start]
cmds = ["reflex run --env prod --backend-host 0.0.0.0 --backend-port $PORT"]
